version: '3.9'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
  
  soap:
    container_name: soap
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    build:
      context: .
      dockerfile: Dockerfile.soap
    ports:
      - 8080:80

volumes:
  mysql: